# NumPy

Read the links: https://numpy.org/doc/stable/user/quickstart.html  and https://numpy.org/doc/stable/user/basics.broadcasting.html  before solving the exercises. 

In [578]:
import numpy as np

### Print out the dimension (number of axes), shape, size and the datatype of the matrix A.

In [579]:
A = np.arange(1, 16).reshape(3,5)

In [580]:
A

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])

In [581]:
print(A.ndim)
print(A.shape)
print(A.size)
print(A.dtype)

2
(3, 5)
15
int64


### Do the following computations on the matrices B and C: 
* Elementwise subtraction. 
* Elementwise multiplication. 
* Matrix multiplication (by default you should use the @ operator).

In [582]:
B = np.arange(1, 10).reshape(3, 3)
C = np.ones((3, 3))*2

print(B)
print()
print(C)

[[1 2 3]
 [4 5 6]
 [7 8 9]]

[[2. 2. 2.]
 [2. 2. 2.]
 [2. 2. 2.]]


In [583]:
print(B - C)  # Elementwise substraction
print()
print(B * C)  # Elementwise multiplication
print()
print(B @ C)  # Matrix multiplication( using @ operator)
print()

[[-1.  0.  1.]
 [ 2.  3.  4.]
 [ 5.  6.  7.]]

[[ 2.  4.  6.]
 [ 8. 10. 12.]
 [14. 16. 18.]]

[[12. 12. 12.]
 [30. 30. 30.]
 [48. 48. 48.]]



### Do the following calculations on the matrix:
* Exponentiate each number elementwise (use the np.exp function).

* Calculate the minimum value in the whole matrix. 
* Calculcate the minimum value in each row. 
* Calculcate the minimum value in each column. 


* Find the index value for the minimum value in the whole matrix (hint: use np.argmin).
* Find the index value for the minimum value in each row (hint: use np.argmin).


* Calculate the sum for all elements.
* Calculate the mean for each column. 
* Calculate the median for each column. 

In [584]:
B = np.arange(1, 10).reshape(3, 3)
print(B)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [585]:
print(np.exp(B))
print(np.min(B)) # minimum value in whole matrix
print(B.min(axis = 1))  # minimum value in each row
print(B.min(axis = 0))  # minimum value in each column
print(np.argmin(B))
print(np.argmin(B, axis = 1)) # minimun value in each row
print(np.sum(B))
print(np.mean(B, axis = 0)) # mean for each column
print(np.median(B, axis = 0)) # median for each column





[[2.71828183e+00 7.38905610e+00 2.00855369e+01]
 [5.45981500e+01 1.48413159e+02 4.03428793e+02]
 [1.09663316e+03 2.98095799e+03 8.10308393e+03]]
1
[1 4 7]
[1 2 3]
0
[0 0 0]
45
[4. 5. 6.]
[4. 5. 6.]


### What does it mean when you provide fewer indices than axes when slicing? See example below.

In [586]:
A = np.arange(1, 16).reshape(3,5)
print(A)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]]


In [587]:
A[1]

array([ 6,  7,  8,  9, 10])

**Answer:**

#Answer:
NumPy interprets this as taking a full slice (i.e., :) along the remaining dimensions.

### Iterating over multidimensional arrays is done with respect to the first axis, so in the example below we iterate trough the rows. If you would like to iterate through the array *elementwise*, how would you do that?

In [588]:
A

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])

In [589]:
for i in A:
    print(i)

[1 2 3 4 5]
[ 6  7  8  9 10]
[11 12 13 14 15]


In [590]:
# Iterate through the array elementwise.

for element in A.flat:
    print(element)

1
2
3
4
5
6
7
8
9
10
11
12
13
14
15


### Explain what the code below does. More specifically, b has three axes - what does this mean? 

In [591]:
a = np.arange(30)
b = a.reshape((2, 3, -1))
print(a)
print()

print(b)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29]

[[[ 0  1  2  3  4]
  [ 5  6  7  8  9]
  [10 11 12 13 14]]

 [[15 16 17 18 19]
  [20 21 22 23 24]
  [25 26 27 28 29]]]


# Answer: 
a is one dimensional array with 30 elements from 0 to 29.
b is 3 axes. 1st axis: 2 refers to the blocks, 2nd axis: 3 refers to the row and 3rd axis: -1 refers to the column which is 5, calucation by numpy as numpy automatically interfer the size based on total no of elements. 

### Broadcasting
**Read the following link about broadcasting: https://numpy.org/doc/stable/user/basics.broadcasting.html#basics-broadcasting**

# Remark on Broadcasting when doing Linear Algebra calculations in Python. 

### From the mathematical rules of matrix addition, the operation below (m1 + m2) does not make sense. The reason is that matrix addition requires two matrices of the same size. In Python however, it works due to broadcasting rules in NumPy. So you must be careful when doing Linear Algebra calculations in Python since they do not follow the "mathematical rules". This can however easily be handled by doing some simple programming, for example validating that two matrices have the same shape is easy if you for instance want to add two matrices. 

In [592]:
m1 = np.array([[1, 2], [3, 4]])
m2 = np.array([1, 1])
print(m1 + m2)

[[2 3]
 [4 5]]


In [593]:
print(m1.shape)
print(m2.shape)

(2, 2)
(2,)


### The example below would also not be allowed if following the "mathematical rules" in Linear Algebra. But it works due to broadcasting in NumPy. 

In [594]:
v1 = np.array([1, 2, 3])
print(v1 + 1)

[2 3 4]


In [595]:
A = np.arange(1, 5).reshape(2,2)
print(A)

b = np.array([2, 2])
print(b)

print(A+b)

[[1 2]
 [3 4]]
[2 2]
[[3 4]
 [5 6]]


# Vector- and matrix algebra Exercises

**Now you are going to create a function that can be reused every time you add or multiply matrices. The function is created so that we do the addition and multiplication according to the rules of vector- and matrix algebra.**

**Create a function "add_mult_matrices" that takes two matrices as input arguments (validate that the input are of the type numpy.ndarray by using the isinstance function), a third argument that is either 'add' or 'multiply' that specifies if you want to add or multiply the matrices (validate that the third argument is either 'add' or 'multiply'). When doing matrix addition, validate that the matrices have the same size. When doing matrix multiplication, validate that the sizes conform (i.e. number of columns in the first matrix is equal to the number of rows in the second matrix).**

In [596]:
def add_mult_matrices(A, B, add_or_multiply):
    
    # Validate that the input are of the type np.ndarray
    if not (isinstance(A, np.ndarray) and isinstance(B, np.ndarray)):
        print('Provide two matrices type of np.ndarray')
        
    #When doing the matrix addition
    if add_or_multiply == 'add': 
        if A.shape != B.shape:
            print('Matrices must have same size')
        else:
            return A + B   
    
    #When doing the matrix multiplication
    elif add_or_multiply == 'multiply':
        if A.shape[1] != B.shape[0]:
            print('Number of columns in the first matrix must be equal to number of rows in the second matrix')
        else:
            return A @ B
    
    else:  
        print("Choose either 'add' or 'multiply'.")     



### Solve all the exercises in chapter 10.1 in the book "Matematik för yrkeshögskolan". 

In [597]:
#Uppgift 10.1.1

x = np.array([4, 3])
print(x)


print(x.ndim) # Dimension of vektor
print(x.shape)
print()

#Beräkna 5x, 3x, 5x + 3x, 8x, 4x - x

multi_5 = 5 * x  
print(multi_5)
print()

multi_3 = 3 * x
print(multi_3)
print()

print(add_mult_matrices(5 * x, 3 * x, 'add'))  #Beräkna 5x + 3x using function
print()

multi_8 = 8 * x
print(multi_8)
print()


print(add_mult_matrices(4 * x, -x, 'add')) #Beräkna (4x - x)



[4 3]
1
(2,)

[20 15]

[12  9]

[32 24]

[32 24]

[12  9]


In [598]:
x_T = x.reshape(-1,1) #Beräkna x^T
print(x_T)



[[4]
 [3]]


In [599]:
print(add_mult_matrices(x, x_T, 'add')) #Beräkna x + x^T

Matrices must have same size
None


In [600]:
norm_x = np.linalg.norm(x) #Beräkna ||x||
print(norm_x)

5.0


In [601]:
# uppgift 10.1.2

v1 = np.array([3, 7, 0, 11])
print(v1)


v = v1.reshape(-1,1)
print(v)



[ 3  7  0 11]
[[ 3]
 [ 7]
 [ 0]
 [11]]


In [602]:
print(v.ndim) # dimension
print(v.shape) # shape


2
(4, 1)


In [603]:
vmulti_2 = 2 * v #Beräkna 2v
print(vmulti_2)

[[ 6]
 [14]
 [ 0]
 [22]]


In [604]:
print(add_mult_matrices(5 * v, 2 * v, 'add'))  #Beräkna 5v + 2v


[[21]
 [49]
 [ 0]
 [77]]


In [605]:
print(add_mult_matrices(4 * v, -2 * v, 'add'))  #Beräkna 4v - 2v


[[ 6]
 [14]
 [ 0]
 [22]]


In [606]:
print(v1) #v^T which is v1

norm_v = np.linalg.norm(v)  #Beräkna ||v||
print(norm_v)

[ 3  7  0 11]
13.379088160259652


In [607]:
#uppgift 10.1.3
v1 = np.array([4, 3, 1, 5])
v2 = np.array([2, 3, 1, 1])
v3 = v1 - v2

norm_v1 = np.linalg.norm(v1)  #Beräkna ||v1||
print(norm_v1)

norm_v3 = np.linalg.norm(v3) #Beräkna ||v1 -v2||
print(norm_v3)

  

7.14142842854285
4.47213595499958


### Solve all the exercises, except 10.2.4, in chapter 10.2 in the book "Matematik för yrkeshögskolan". 

In [608]:
A = np.array([[2, 1, -1], [1, -1, 1]])
B = np.array([[4, -2, 1], [2, -4, -2]])

C = np.array([[1, 2], [2, 1]])
D = np.array([[3, 4], [4, 3]])
E = np.array([1,2])
I = np.array([[1,0], [0,1]])


multi_2A = 2 * A  # Beräkna 2A
print(multi_2A)



[[ 4  2 -2]
 [ 2 -2  2]]


In [609]:
print(add_mult_matrices(B, -2 * A, 'add'))  # B-2A

[[ 0 -4  3]
 [ 0 -2 -4]]


In [610]:
print(add_mult_matrices(3 * C, -2 * E, 'add'))  #3C - 2E

Matrices must have same size
None


In [611]:
print(add_mult_matrices(2 * D, -3 * C, 'add')) #2D - 3C


[[3 2]
 [2 3]]


In [612]:
D_T = D.transpose()
print(add_mult_matrices(D_T, 2 * D, 'add'))  #D^T + 2D


[[ 9 12]
 [12  9]]


In [613]:
C_T = C.transpose()
print(add_mult_matrices((2 * C_T), (-2 * D_T), 'add'))  #2C^T - 2D^T

[[-4 -4]
 [-4 -4]]


In [614]:
A_T = A.transpose()
print(add_mult_matrices(A_T, -B, 'add')) #A^T - B

Matrices must have same size
None


In [615]:
print(add_mult_matrices(A, C, 'multiply'))  #Beräkna AC

Number of columns in the first matrix must be equal to number of rows in the second matrix
None


In [616]:
print(add_mult_matrices(C, D, 'multiply'))  #Beräkna CD



[[11 10]
 [10 11]]


In [617]:
print(add_mult_matrices(C, B, 'multiply'))  #Beräkna CB


[[  8 -10  -3]
 [ 10  -8   0]]


In [618]:
print(add_mult_matrices(C, I, 'multiply'))   #Beräkna CI


[[1 2]
 [2 1]]


In [619]:
B_T = B.transpose()
print(add_mult_matrices(A, B_T, 'multiply'))  #Beräkna AB^T


[[5 2]
 [7 4]]


In [620]:
#Uppgift 10.2.2

A = np.array([[2, 3, 4], [5, 4, 1]])
A_T = A.transpose()
print(add_mult_matrices(A, A_T, 'multiply'))  #Beräkna AA^T




[[29 26]
 [26 42]]


In [621]:
#uppgift 10.2.3

A = np.array([[1, 2], [2,4]])
B = np.array([[2, 1], [1, 3]])
C = np.array([[4, 3], [0, 2]])

AB = A @ B
AC = A @ C

# Verifiera AB = AC using the function

print(f'AB:','\n', add_mult_matrices(A, B, 'multiply'))

print(f'AC:', '\n', add_mult_matrices(A, C, 'multiply'))

print(AB.all() == AC.all())
print((B != C).all())


AB: 
 [[ 4  7]
 [ 8 14]]
AC: 
 [[ 4  7]
 [ 8 14]]
True
True


### Copies and Views
Read the following link: https://numpy.org/doc/stable/user/basics.copies.html

**Basic indexing creates a view, How can you check if v1 and v2 is a view or copy? If you change the last element in v2 to 123, will the last element in v1 be changed? Why?**

In [622]:
v1 = np.arange(4)
v2 = v1[-2:]
print(v1)
print(v2)

[0 1 2 3]
[2 3]


# Answer:
  v2 is a view of v1 because the basic slicing on  (v1[-2:]). 
If I change the last element in v2 to 123, the last element in v1 be changed because both array share the same data memory.

In [623]:
# The base attribute of a view returns the original array while it returns None for a copy.
print(v1.base)
print(v2.base)

None
[0 1 2 3]


In [624]:
# The last element in v1 will be changed aswell since v2 is a view, meaning they share the same data buffer.
v2[-1] = 123
print(v1)
print(v2)

[  0   1   2 123]
[  2 123]
